name: saves_america
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.45.2
  - libzlib=1.2.13
  - pyarrow=5.0.0
  #- ncurses=6.4.20240210
  - openssl=3.2.1
  - pip=24.0
  - python=3.10.5
  #- readline=8.2
  - setuptools=69.2.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
    - anyio==4.3.0
    - altair==5.3.0
    - appnope==0.1.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blinker==1.7.0
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - comm==0.2.2
    - contourpy==1.2.0
    - cycler==0.12.1
    - dash==2.16.1
    - dash-bootstrap-components==1.5.0
    - dash_vega_components==0.8.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - flask==3.0.2
    - fastparquet==2024.2.0
    - Flask-Caching==2.1.0
    - fonttools==4.50.0
    - fqdn==1.5.1
    - idna==3.6
    - importlib-metadata==7.1.0
    - ipykernel==6.29.4
    - ipython==8.22.2
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.19.1
    - jinja2==3.1.3
    - json5==0.9.24
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.4
    - jupyter-server==2.13.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.0.10
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.4
    - kiwisolver==1.4.5
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.3
    - nest-asyncio==1.6.0
    - notebook-shim==0.2.4
    - numpy==1.26.4
    - overrides==7.7.0
    - packaging==24.0
    - pandas==2.2.1
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pexpect==4.9.0
    - pillow==10.2.0
    - platformdirs==4.2.0
    - plotly==5.20.0
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==15.0.2
    - pycparser==2.21
    - pygments==2.17.2
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - referencing==0.34.0
    - requests==2.31.0
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.0
    - scipy==1.12.0
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.

